[default]
bootstrap.servers=broker:9092
# 'auto.offset.reset=earliest' to start reading from the beginning of
# the topic if no committed offsets exist.
auto.offset.reset=earliest

[monitor]
group.id=monitor

[video-service]
group.id=video-service

[telemetry]
group.id=telemetry

[data-collector]
group.id=data-collector

[validator]
group.id=validator

[chipher]
group.id=chipher

[communication]
group.id=communication

[communication-volan]
group.id=communication-volan

[chipher-volan]
group.id=chipher-volan

[analysis-volan]
group.id=analysis-volan

[distributor-volan]
group.id=distributor-volan

[communication-sec]
group.id=communication-sec

[chipher-sec]
group.id=chipher-sec

[handler-sec]
group.id=handler-sec

[activate-sec]
group.id=activate-sec

[events-sec]
group.id=events-sec

[distributor-sec]
group.id=distributor-sec

[validator-sec]
group.id=validator-sec

[communication-robot]
group.id=communication-robot

[chipher-robot]
group.id=chipher-robot

[drivers-robot]
group.id=drivers-robot

[nav-robot]
group.id=nav-robot

[controller-robot]
group.id=controller-robot

[gear-robot]
group.id=gear-robot

[control-sys-robot]
group.id=control-sys-robot

[speakers-robot]
group.id=speakers-robot

[communication-repair]
group.id=communication-repair

[handle-repair]
group.id=handle-repair

[activate-repair]
group.id=activate-repair

[analysis-repair]
group.id=analysis-repair

[start-repair]
group.id=start-repair

[communication-grif]
group.id=communication-grif

[chipher-grif]
group.id=chipher-grif

[handler-grif]
group.id=handler-grif

[poweroff-grif]
group.id=poweroff-grif

[authentication]
group.id=authentication

[authorization]
group.id=authorization

[chipher-terminal]
group.id=chipher-terminal

[communication-terminal]
group.id=communication-terminal

[handle-command]
group.id=handle-command

[user]
group.id=user

[validator-card]
group.id=validator-card

[communication-vetrolov]
group.id=communication-vetrolov

[chipher-vetrolov]
group.id=chipher-vetrolov

[handler-vetrolov]
group.id=handler-vetrolov

[generator-vetrolov]
group.id=generator-vetrolov

[controller-vetrolov]
group.id=controller-vetrolov

[battery-vetrolov]
group.id=battery-vetrolov

[communication-diagnostic]
group.id=communication-diagnostic

[chipher-diagnostic]
group.id=chipher-diagnostic

[validator-diagnostic]
group.id=validator-diagnostic

[camera-diagnostic]
group.id=camera-diagnostic